# Generated by Django 5.1 on 2024-12-21 19:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=80)),
                ('correo_institucion', models.EmailField(max_length=254)),
                ('telefono_institucion', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('nro_personas', models.IntegerField(default=1)),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
                ('hora_inscripcion', models.TimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO_ASISTEN', 'No Asisten')], default='RESERVADO', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('institucion_asociada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.institucion')),
            ],
        ),
    ]
